### ISSUE TITLE
Disable PointsCoreDebug console messages

### ISSUE THREAD

**Issue by joex92** [marcangeloh/PointsCore#2]
Hi,
since I added the UpgradableTools plugin and everything else I've been having these Debug messages on console, sometimes is annoying and honestly I don't remember if I enabled it or it just enabled itself but I haven't found anywhere how to disable them... Can debugging be disabled? (sorry if this is an "obvious" question)

**Comment by marcangeloh** [comment]
Hey joex92, unfortunately at the moment upgradeableTools is discontinued until next year. I do believe however that you should be capable of turning it off or at least reducing it in the configuration files. I am aware that there are a few bugs that must be fixed however I no longer play the game and no longer code for it. I also noticed a lack of interest in this plugin in general and therefore did not feel forced to proceed with it's development. Thanks and kind regards, marcangeloh

**Comment by joex92** [comment]
oh you mean until 2022? that's a bummer... but ok... I'll think about keeping it then... Still thanks for the plugin... 1.17 seems that is going to be fun, maybe think about coming back to coding for Minecraft, idk, just a suggestion... take care... 👍

**Comment by marcangeloh** [comment]
I will be coding an update for PointsCore and UpgradeableTools shortly with most of the community feedback included. And many bug fixes. Please open a new issue should you have any more bugs with the newer version.
